apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-1-28-green
  labels:
    app: nginx-1-28
    version: green
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
      version: green
  template:
    metadata:
      labels:
        app: nginx
        version: green
    spec:
      containers:
        - name: nginx
          image: <+artifact.image>
          ports:
            - containerPort: 8080

