apiVersion: apps/v1
kind: Deployment
metadata:
  name: <+service.name>-green
  labels:
    app: <+service.name>
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: <+service.name>
      version: green
  template:
    metadata:
      labels:
        app: <+service.name>
        version: green
    spec:
      containers:
        - name: <+service.name>
          image: <+artifact.image>
          ports:
            - containerPort: <+pipeline.variables.port>
