apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
    version: green # Initially points to blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
