apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
    version: blue  # Initially points to blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: <+pipeline.variables.port>
