apiVersion: v1
kind: Service
metadata:
  name: <+service.name>
spec:
  selector:
    app: <+service.name>
    version: blue  # Initially points to blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
